---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas
  labels:
    app  : my-k8s-application
    env  : prod
    owner: DenisAstahov
spec:
  replicas: 3
  selector:
    matchLabels:
      name: MyApp
      project: cia
  template:
    metadata:
      labels:
        name: MyApp
        project: cia
    spec:
      containers:
        - name : cia-web
          image: thread83/ip-show:v01
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    name: MyApp
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30010

